//! The formulas the invariant tests run over: one of each construct the
//! fork's source mapping knows, more shapes the stops treat specially,
//! and the oracle's synthetic fixtures.
#![allow(dead_code, clippy::unwrap_used, clippy::non_ascii_literal)]

/// `katex/tests/source_locs.rs`'s formulas: one of each construct the
/// source mapping knows.
pub const FORMULAS: &[&str] = &[
    "ab",
    r"\frac{a}{b}",
    r"\frac ab",
    r"a\over b",
    r"{\over b}",
    r"{a\over}",
    r"a\above 2pt b",
    r"{n\choose k}",
    "x^2_i",
    "^2",
    "x'",
    "x''^2",
    "x²",
    "x₁₂",
    r"\sqrt[3]{x}",
    r"\sqrt x",
    r"\left(\frac{a}{b}\right)",
    r"\left(a\middle|b\right)",
    r"\dots",
    r"a\iff b",
    r"\neq",
    r"\alpha x",
    r"\def\x{ab}\x",
    r"\def\x#1{#1+#1}\x{y}",
    r"\newcommand{\br}[1]{\langle #1|}\br{x}",
    r"\bra{x}",
    r"\text{สวัสดี x}",
    r"\text{a $x$ b}",
    r"\begin{pmatrix}a&b\\c&\end{pmatrix}",
    r"\begin{pmatrix}&\\&\end{pmatrix}",
    r"\begin{cases}a&b\\c&d\end{cases}",
    r"\begin{aligned}a&=b\\&=c\end{aligned}",
    r"\begin{array}{cc}a&b\end{array}",
    r"\color{red}{x}",
    r"\color{red} x y",
    r"\textcolor{red}{x}",
    r"\mathbf{ab}",
    r"\bf ab",
    r"\displaystyle x",
    r"\large x",
    r"\operatorname{sin}x",
    r"\overset{a}{b}",
    r"\verb|x|",
    r"\tag{1} x",
    "{}",
    r"\frac{}{}",
    "x^{}",
    r"\hat{x}",
    "é",
    r"\sum_{i=1}^n i",
    r"\mathrm{d}x",
    r"\char`a",
    r"\kern1em x",
    r"\rule{1em}{2em}",
    r"\hbox{x}",
    r"\boxed{x}",
    r"\xrightarrow[b]{a}",
    r"\overbrace{x}^{y}",
    r"\mathchoice{a}{b}{c}{d}",
    r"\phantom{x}",
    r"\not=",
    r"\big(",
    r"\cancel{x}",
    r"a\\b",
    r"\begin{CD}A @>f>> B\\@VVV @AAA\\C @= D\end{CD}",
    r"\begin{CD}A @<a<< B @>>b> C\\@| @AcAA @VVdV\\D @= E @>>> F\end{CD}",
    r"\begin{align}a&=b\tag{1}\\c&=d\end{align}",
    r"\begin{gather}a\\b\end{gather}",
    r"\begin{smallmatrix}a&b\end{smallmatrix}",
    r"\begin{array}{|c|}\hline a\\\hline\end{array}",
    r"\begin{matrix}a\\[1em]b\end{matrix}",
    r"\begin{matrix}\end{matrix}",
    r"\begin{rcases}a\end{rcases}",
    r"\begin{gathered}a\end{gathered}",
    r"\begin{bmatrix*}[r]a\end{bmatrix*}",
    r"\begin{equation}a\end{equation}",
    r"\left.\right.",
    r"\sqrt[]{}",
    "a_{}^{}",
    "x^{y^{z}}",
    r"\overline{}",
    r"\text{--- ''}",
    r"\textbf{a}",
    r"\boldsymbol{x}",
    r"\stackrel{a}{=}",
    r"\underbrace{x}_{y}",
    r"\xleftarrow{}",
    r"\pmb{x}",
    r"\raisebox{1em}{x}",
    r"\rlap{x}",
    r"\smash{x}",
    r"\vcenter{x}",
    r"\vphantom{x}",
    r"\mathop{x}",
    r"\binom{a}{b}",
    r"\genfrac(]{0pt}{2}{a}{b}",
    r"\cfrac{a}{b}",
    r"\operatorname*{lim}_x",
    r"\lim\limits_{x}",
    r"\Set{x|y}",
    r"\braket{a|b}",
    r"\colorbox{red}{x}",
    r"\fcolorbox{red}{blue}{x}",
    r"\kern-1em x",
    r"\hspace{1em}x",
    r"\mathring{a}",
    r"\ddots\vdots\cdots\dotsb",
    r"\TextOrMath{a}{b}",
    r"\href{http://a}{x}",
    r"\url{http://a}",
    r"\includegraphics{a.png}",
    r"\htmlClass{a}{x}",
    r"\phase{x}",
    r"\angl{n}",
    r"\sqrt{\smash[b]{y}}",
    r"\begingroup a\endgroup",
    r"\def\x#1.{#1}\x a.",
    r"\let\y=a\y",
    r"\gdef\z{q}\z",
    r"\mathchoice{a}{b}{c}{d}",
];

/// More shapes the stops treat specially.
pub const EDIT_FORMULAS: &[&str] = &[
    r"\begin{matrix}a&&b\end{matrix}",
    r"\begin{pmatrix}a\\\end{pmatrix}",
    r"\text{ไทย}",
    r"\text{สวัสดี x}",
    "a={}b",
    "{}^{14}C",
    r"\sqrt\frac ab",
    r"x^\frac ab",
    r"\frac\alpha  b",
    r"\textcolor{red}{}",
    r"\operatorname{}",
    r"\left\langle \right\rangle",
    r"\Set{x|y}",
    r"\boxed{\frac{a}{b}}",
    r"a\\b\over c",
    r"x\tag*{a}",
    r"\text{a\ b}",
    r"\mathrm{d}x\,\mathrm{d}y",
    "x_{a_{b_c}}",
    r"\left(\begin{matrix}a\end{matrix}\right)^2",
    r"\displaystyle\sum_{n=1}^\infty \frac1{n^2}",
    r"\begin{bmatrix}a & b \\ c & d\end{bmatrix}",
    "\\begin{bmatrix}\n1 & 2 \\\\\n3 & 4\n\\end{bmatrix}",
    r"\begin{pmatrix}1 \\ 2 \\\end{pmatrix}",
    r"\begin{bmatrix}a & & b \\ & c\end{bmatrix}^T",
    r"\begin{vmatrix}a&b\\c&d\end{vmatrix}",
    r"\begin{Bmatrix}{a} & \end{Bmatrix}",
    r"\begin{smallmatrix}a & b\end{smallmatrix}",
    r"\begin{Vmatrix}x\end{Vmatrix}",
    "(a b",
    "[1 -1]^T",
    r"\left[a+b\right]",
    r"f(x;y) = \{a, \lvert b\rvert\}",
    r"\Vert x + \vert y",
    "[0,1)",
];

pub fn fixtures() -> Vec<(String, bool)> {
    let json: serde_json::Value =
        serde_json::from_str(include_str!("../../../oracle/fixtures.json")).unwrap();
    json.as_array()
        .unwrap()
        .iter()
        .map(|case| {
            (
                case["tex"].as_str().unwrap().to_owned(),
                case["display"].as_bool().unwrap_or(false),
            )
        })
        .collect()
}

/// Every formula, inline and display.
pub fn corpus() -> Vec<(String, bool)> {
    let mut out: Vec<(String, bool)> = FORMULAS
        .iter()
        .chain(EDIT_FORMULAS)
        .flat_map(|tex| [((*tex).to_owned(), false), ((*tex).to_owned(), true)])
        .collect();
    out.extend(fixtures());
    out
}
