import {
  Airplane, Alarm, Alien, Anchor, Archive, Article, Atom, Backpack, Balloon,
  Bandaids, Bank, Barbell, Basketball, Bell, Binary, Binoculars, Bird, Boat,
  Bone, Book, BookBookmark, BookOpen, Books, BracketsCurly, Brain, Bridge,
  Briefcase, Broadcast, Bug, Buildings, Butterfly, Cake, Calculator, Camera,
  Car, Carrot, CastleTurret, Cat, Chalkboard, ChalkboardTeacher, ChartBar,
  ChartLine, ChartLineUp, ChartPie, ChartScatter, ChatCircle, ChatsCircle,
  ChefHat, Church, Circuitry, Cloud, CloudRain, Code, Coffee, Coins, Compass,
  CompassTool, Confetti, CookingPot, Cpu, Crown, Cube, CurrencyDollar,
  Database, Desktop, Detective, Diamond, DiceFive, Dna, Dog, Drop, Ear,
  Engine, Envelope, Exam, Eye, Factory, Feather, FileCode, FilmSlate, Fire,
  FirstAid, Fish, Flag, Flask, Flower, FolderOpen, Football, ForkKnife,
  Function, GameController, Gavel, Gear, Ghost, Gift, GitBranch, Globe,
  GlobeHemisphereWest, GraduationCap, Graph, Guitar, Hammer, Handshake,
  HardDrives, Headphones, Heart, Heartbeat, Highlighter, Horse, Hourglass,
  HouseLine, IceCream, Infinity as InfinityIcon, Joystick, Key, Keyboard,
  Laptop, Leaf, Lightbulb, Lightning, LockKey, MagnifyingGlass, MapPin,
  MapTrifold, MaskHappy, MathOperations, Medal, Megaphone, Microphone,
  Microscope, Money, Moon, Mountains, MusicNote, MusicNotes, Network,
  Newspaper, NotePencil, Notebook, Package, PaintBrush, Palette, PawPrint,
  PenNib, PencilSimple, Percent, PersonSimpleBike, PersonSimpleRun,
  PersonSimpleSwim, Pi, PianoKeys, PiggyBank, Pill, Pizza, Planet, Plant,
  Pulse, PuzzlePiece, Quotes, Rabbit, Receipt, Robot, RocketLaunch, Ruler,
  Scales, Scroll, ShareNetwork, Shapes, ShieldCheck,
  ShoppingCart, Sigma, Skull, Sneaker, Snowflake, SoccerBall, Sparkle, Star,
  SteeringWheel, Stethoscope, Storefront, Student, Sun, Sword, Syringe,
  Target, TennisBall, Terminal, TestTube, TextAa, Thermometer, Timer,
  Toolbox, Tooth, TrainSimple, Translate, Tree, TreeStructure, TrendUp,
  Triangle, Trophy, Umbrella, Users, UsersThree, VideoCamera, Virus,
  VirtualReality, Volleyball, Wallet, Waveform, Waves, Wind, Wrench,
  type Icon,
} from "@phosphor-icons/react";

export interface IconCatalogEntry {
  name: string;
  Icon: Icon;
  /** Extra lowercase search terms beyond the name itself. */
  keywords: string[];
}

const e = (name: string, Icon: Icon, ...keywords: string[]): IconCatalogEntry => ({
  name,
  Icon,
  keywords,
});

/** Curated Phosphor icons for subject identities, ordered by theme. */
export const ICON_CATALOG: IconCatalogEntry[] = [
  // Study & school
  e("Book", Book, "read", "study"),
  e("BookOpen", BookOpen, "read", "study"),
  e("Books", Books, "library", "read"),
  e("BookBookmark", BookBookmark, "read", "save"),
  e("GraduationCap", GraduationCap, "degree", "school", "uni"),
  e("Student", Student, "school", "learn"),
  e("Chalkboard", Chalkboard, "class", "teach"),
  e("ChalkboardTeacher", ChalkboardTeacher, "class", "teach", "lecture"),
  e("Exam", Exam, "test", "quiz", "assessment"),
  e("PencilSimple", PencilSimple, "write", "edit"),
  e("PenNib", PenNib, "write", "ink", "design"),
  e("Highlighter", Highlighter, "marker", "notes"),
  e("NotePencil", NotePencil, "notes", "write"),
  e("Notebook", Notebook, "notes", "journal"),
  e("Backpack", Backpack, "bag", "school"),
  e("Binoculars", Binoculars, "search", "explore"),
  e("Lightbulb", Lightbulb, "idea", "insight"),
  e("Brain", Brain, "mind", "psychology", "cognition", "neuro"),
  e("Target", Target, "goal", "aim"),
  e("Trophy", Trophy, "win", "award"),
  e("Medal", Medal, "award", "honor"),
  e("Star", Star, "favorite"),
  e("Sparkle", Sparkle, "magic", "new"),
  e("Flag", Flag, "milestone", "country"),
  e("Timer", Timer, "stopwatch", "time"),
  e("Hourglass", Hourglass, "time", "deadline"),
  e("Alarm", Alarm, "clock", "time"),
  // Maths & data
  e("Calculator", Calculator, "math", "arithmetic"),
  e("MathOperations", MathOperations, "math", "plus", "minus"),
  e("Function", Function, "math", "calculus"),
  e("Sigma", Sigma, "math", "sum", "statistics"),
  e("Pi", Pi, "math", "geometry"),
  e("Infinity", InfinityIcon, "math", "limit"),
  e("Percent", Percent, "math", "statistics", "probability"),
  e("ChartLine", ChartLine, "graph", "data", "statistics"),
  e("ChartBar", ChartBar, "graph", "data", "statistics"),
  e("ChartPie", ChartPie, "graph", "data", "statistics"),
  e("ChartScatter", ChartScatter, "graph", "data", "statistics"),
  e("TrendUp", TrendUp, "growth", "graph"),
  e("Ruler", Ruler, "measure", "geometry"),
  e("CompassTool", CompassTool, "geometry", "draft", "design"),
  e("Cube", Cube, "3d", "geometry"),
  e("Shapes", Shapes, "geometry"),
  e("Triangle", Triangle, "geometry"),
  // Science
  e("Atom", Atom, "physics", "chemistry", "science"),
  e("Flask", Flask, "chemistry", "lab", "science"),
  e("TestTube", TestTube, "chemistry", "lab", "science"),
  e("Microscope", Microscope, "biology", "lab", "science"),
  e("Dna", Dna, "biology", "genetics"),
  e("Virus", Virus, "biology", "medicine", "microbe"),
  e("Planet", Planet, "space", "astronomy"),
  e("RocketLaunch", RocketLaunch, "space", "startup", "launch"),
  e("MagnifyingGlass", MagnifyingGlass, "search", "research"),
  e("Thermometer", Thermometer, "temperature", "weather"),
  e("Lightning", Lightning, "electricity", "energy", "physics"),
  e("Fire", Fire, "flame", "energy"),
  e("Drop", Drop, "water", "liquid"),
  e("Snowflake", Snowflake, "cold", "winter"),
  e("Wind", Wind, "weather", "air"),
  e("Sun", Sun, "light", "day", "weather"),
  e("Moon", Moon, "night", "astronomy"),
  e("CloudRain", CloudRain, "weather", "meteorology"),
  e("Waves", Waves, "ocean", "sea", "physics"),
  e("Mountains", Mountains, "geology", "geography", "outdoors"),
  // Nature
  e("Leaf", Leaf, "nature", "eco", "environment"),
  e("Plant", Plant, "nature", "botany", "grow"),
  e("Tree", Tree, "nature", "forest"),
  e("Flower", Flower, "nature", "botany"),
  e("PawPrint", PawPrint, "animal", "pet", "vet"),
  e("Bug", Bug, "insect", "debug", "entomology"),
  e("Fish", Fish, "marine", "animal"),
  e("Bird", Bird, "animal", "ornithology"),
  e("Butterfly", Butterfly, "insect", "nature"),
  e("Cat", Cat, "animal", "pet"),
  e("Dog", Dog, "animal", "pet"),
  e("Horse", Horse, "animal"),
  e("Rabbit", Rabbit, "animal"),
  // Medicine & health
  e("Heartbeat", Heartbeat, "medicine", "health", "cardio"),
  e("Pulse", Pulse, "medicine", "health", "signal"),
  e("FirstAid", FirstAid, "medicine", "health", "emergency"),
  e("Pill", Pill, "medicine", "pharmacy", "drug"),
  e("Syringe", Syringe, "medicine", "vaccine"),
  e("Stethoscope", Stethoscope, "medicine", "doctor"),
  e("Bandaids", Bandaids, "medicine", "injury"),
  e("Heart", Heart, "love", "health"),
  e("Tooth", Tooth, "dental", "dentist"),
  e("Eye", Eye, "vision", "optometry", "see"),
  e("Ear", Ear, "hearing", "audiology"),
  e("Bone", Bone, "anatomy", "skeleton"),
  // Computing
  e("Code", Code, "programming", "software", "dev"),
  e("Terminal", Terminal, "cli", "shell", "programming"),
  e("Cpu", Cpu, "processor", "hardware", "computer"),
  e("Database", Database, "sql", "data", "storage"),
  e("HardDrives", HardDrives, "storage", "server"),
  e("Circuitry", Circuitry, "electronics", "hardware", "circuit"),
  e("Robot", Robot, "ai", "machine", "automation"),
  e("Binary", Binary, "bits", "computer", "logic"),
  e("BracketsCurly", BracketsCurly, "code", "json", "programming"),
  e("FileCode", FileCode, "code", "source", "programming"),
  e("GitBranch", GitBranch, "version", "git", "branch"),
  e("Graph", Graph, "network", "nodes", "discrete"),
  e("TreeStructure", TreeStructure, "hierarchy", "data structure"),
  e("ShareNetwork", ShareNetwork, "network", "graph"),
  e("Network", Network, "internet", "topology"),
  e("Cloud", Cloud, "computing", "weather"),
  e("LockKey", LockKey, "security", "crypto", "auth"),
  e("ShieldCheck", ShieldCheck, "security", "safety"),
  e("Detective", Detective, "mystery", "investigate", "forensics"),
  e("Broadcast", Broadcast, "signal", "radio", "network"),
  e("Desktop", Desktop, "computer", "monitor"),
  e("Laptop", Laptop, "computer"),
  e("Keyboard", Keyboard, "typing", "computer"),
  e("GameController", GameController, "games", "gaming"),
  e("Joystick", Joystick, "games", "gaming", "arcade"),
  e("VirtualReality", VirtualReality, "vr", "xr", "immersive"),
  // Business & law
  e("Bank", Bank, "finance", "economics", "institution"),
  e("Briefcase", Briefcase, "business", "work", "job"),
  e("ChartLineUp", ChartLineUp, "finance", "growth", "stocks"),
  e("Coins", Coins, "money", "finance", "economics"),
  e("CurrencyDollar", CurrencyDollar, "money", "finance", "economics"),
  e("PiggyBank", PiggyBank, "savings", "finance"),
  e("Receipt", Receipt, "accounting", "invoice"),
  e("ShoppingCart", ShoppingCart, "commerce", "retail"),
  e("Storefront", Storefront, "shop", "commerce", "marketing"),
  e("Handshake", Handshake, "deal", "negotiation", "partnership"),
  e("Scales", Scales, "law", "justice", "balance"),
  e("Gavel", Gavel, "law", "court", "judge"),
  e("Money", Money, "cash", "finance"),
  e("Wallet", Wallet, "money", "finance"),
  // People & language
  e("Users", Users, "people", "group", "sociology"),
  e("UsersThree", UsersThree, "people", "team", "community"),
  e("ChatCircle", ChatCircle, "talk", "communication"),
  e("ChatsCircle", ChatsCircle, "discussion", "communication"),
  e("Translate", Translate, "language", "linguistics"),
  e("Article", Article, "writing", "essay", "journalism"),
  e("TextAa", TextAa, "typography", "language", "writing"),
  e("Quotes", Quotes, "literature", "citation", "writing"),
  e("Newspaper", Newspaper, "news", "journalism", "media"),
  e("Scroll", Scroll, "history", "ancient", "document"),
  e("Feather", Feather, "writing", "literature", "quill"),
  e("Globe", Globe, "world", "geography", "international"),
  e("GlobeHemisphereWest", GlobeHemisphereWest, "world", "geography", "earth"),
  e("MapTrifold", MapTrifold, "geography", "navigation"),
  e("MapPin", MapPin, "location", "place"),
  e("Compass", Compass, "navigation", "direction"),
  e("Church", Church, "religion", "theology"),
  e("CastleTurret", CastleTurret, "history", "medieval"),
  e("Crown", Crown, "history", "royalty", "monarchy"),
  e("Sword", Sword, "history", "war", "medieval"),
  // Arts & media
  e("Palette", Palette, "art", "paint", "color"),
  e("PaintBrush", PaintBrush, "art", "paint", "design"),
  e("Camera", Camera, "photography", "photo"),
  e("FilmSlate", FilmSlate, "movie", "cinema", "film"),
  e("VideoCamera", VideoCamera, "video", "film", "recording"),
  e("MusicNote", MusicNote, "music", "song"),
  e("MusicNotes", MusicNotes, "music", "song"),
  e("PianoKeys", PianoKeys, "music", "piano", "instrument"),
  e("Guitar", Guitar, "music", "instrument"),
  e("Microphone", Microphone, "audio", "speech", "podcast"),
  e("Headphones", Headphones, "audio", "music", "listening"),
  e("Waveform", Waveform, "audio", "sound", "signal"),
  e("MaskHappy", MaskHappy, "theatre", "drama", "acting"),
  // Sport & movement
  e("Barbell", Barbell, "gym", "fitness", "exercise"),
  e("Basketball", Basketball, "sport", "ball"),
  e("SoccerBall", SoccerBall, "sport", "football"),
  e("TennisBall", TennisBall, "sport"),
  e("Volleyball", Volleyball, "sport"),
  e("Football", Football, "sport", "american"),
  e("PersonSimpleRun", PersonSimpleRun, "running", "sport", "exercise"),
  e("PersonSimpleBike", PersonSimpleBike, "cycling", "sport", "exercise"),
  e("PersonSimpleSwim", PersonSimpleSwim, "swimming", "sport", "exercise"),
  e("Sneaker", Sneaker, "shoe", "running", "sport"),
  // Engineering & transport
  e("Wrench", Wrench, "tools", "mechanic", "fix"),
  e("Hammer", Hammer, "tools", "build"),
  e("Gear", Gear, "settings", "mechanical", "engineering"),
  e("Toolbox", Toolbox, "tools", "workshop"),
  e("Buildings", Buildings, "city", "architecture", "urban"),
  e("Factory", Factory, "industry", "manufacturing"),
  e("HouseLine", HouseLine, "home", "architecture"),
  e("Bridge", Bridge, "civil", "engineering", "structure"),
  e("Airplane", Airplane, "flight", "travel", "aviation"),
  e("Car", Car, "vehicle", "automotive", "transport"),
  e("TrainSimple", TrainSimple, "rail", "transport"),
  e("Boat", Boat, "ship", "marine", "transport"),
  e("Anchor", Anchor, "marine", "nautical", "sea"),
  e("SteeringWheel", SteeringWheel, "driving", "vehicle"),
  e("Engine", Engine, "motor", "mechanical", "automotive"),
  // Food
  e("Coffee", Coffee, "drink", "cafe", "caffeine"),
  e("ForkKnife", ForkKnife, "food", "dining", "restaurant"),
  e("CookingPot", CookingPot, "food", "cooking", "kitchen"),
  e("ChefHat", ChefHat, "cooking", "culinary", "kitchen"),
  e("Pizza", Pizza, "food"),
  e("Carrot", Carrot, "food", "vegetable", "nutrition"),
  e("IceCream", IceCream, "food", "dessert"),
  e("Cake", Cake, "food", "dessert", "birthday"),
  // Misc
  e("Key", Key, "unlock", "access", "crypto"),
  e("Umbrella", Umbrella, "rain", "insurance", "protection"),
  e("Gift", Gift, "present", "surprise"),
  e("Ghost", Ghost, "spooky", "halloween"),
  e("Alien", Alien, "space", "ufo"),
  e("Skull", Skull, "death", "anatomy", "pirate"),
  e("Diamond", Diamond, "gem", "precious"),
  e("Bell", Bell, "notification", "alert"),
  e("Megaphone", Megaphone, "announcement", "marketing"),
  e("Package", Package, "box", "delivery", "logistics"),
  e("Archive", Archive, "storage", "old", "records"),
  e("FolderOpen", FolderOpen, "files", "documents"),
  e("Envelope", Envelope, "mail", "letter", "email"),
  e("PuzzlePiece", PuzzlePiece, "puzzle", "logic", "games"),
  e("DiceFive", DiceFive, "random", "probability", "games"),
  e("Balloon", Balloon, "party", "celebration"),
  e("Confetti", Confetti, "party", "celebration"),
];

export const ICON_BY_NAME = new Map(ICON_CATALOG.map((c) => [c.name, c.Icon]));
