import { brand, muted, type ThemeSpec } from "./tokens";

export const popoverTooltips: ThemeSpec = {
  // Tooltips (the maths popover, the completion list). `&.cm-editor` beats
  // the base theme's light-mode tooltip rules.
  "&.cm-editor .cm-tooltip.cm-math-tools, &.cm-editor .cm-tooltip.cm-tooltip-autocomplete": {
    backgroundColor: "var(--color-popover)",
    color: "var(--color-popover-foreground)",
    border: "1px solid var(--color-border)",
    borderRadius: "12px",
    boxShadow: "var(--shadow-lg)",
    fontFamily: "var(--font-sans)",
  },

  ".cm-math-tools": {
    width: "352px",
    maxWidth: "calc(100vw - 16px)",
    padding: "8px",
    overflowX: "hidden",
    overflowY: "auto",
    fontSize: "12px",
    lineHeight: "1.4",
  },
  ".cm-math-tools.cm-math-tools-hidden, &.cm-math-command .cm-math-tools": { display: "none" },
  // Under the visual field: no preview, the field is the preview.
  ".cm-math-tools-visual .cm-math-preview, .cm-math-tools-visual .cm-math-error-text": { display: "none" },
  ".cm-math-tools-visual .cm-math-recents": { marginTop: "0" },
  ".cm-math-tools-visual .cm-math-recents[hidden] + .cm-math-tabbar": {
    marginTop: "0",
    paddingTop: "0",
    borderTop: "0",
  },
  ".cm-math-preview": {
    minHeight: "36px",
    maxHeight: "160px",
    overflow: "auto",
    padding: "6px 8px",
    borderRadius: "8px",
    backgroundColor: "var(--color-surface)",
    display: "flex",
    alignItems: "center",
    fontSize: "14px",
  },
  // Auto margins centre it and keep a wide formula's start reachable.
  ".cm-math-preview > *": { margin: "auto", flex: "none" },
  ".cm-math-preview-stale": { opacity: "0.45" },
  ".cm-math-preview-empty": { color: muted, fontSize: "12px" },
  ".cm-math-error-text": {
    color: "var(--color-destructive)",
    fontSize: "11px",
    marginTop: "4px",
    overflowWrap: "anywhere",
  },
  ".cm-math-error-text:empty": { display: "none" },
  ".cm-math-matrix-kinds": { display: "flex", flexWrap: "wrap", gap: "2px" },
  ".cm-math-tabbar": {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginTop: "6px",
    paddingTop: "6px",
    borderTop: "1px solid var(--color-border-subtle)",
  },
  // One row that scrolls sideways; faded by `syncScrollFade` (`index.css`).
  ".cm-math-tabs": {
    flex: "1",
    minWidth: "0",
    display: "flex",
    gap: "2px",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  ".cm-math-tabs::-webkit-scrollbar": { display: "none" },
  ".cm-math-tabs .cm-math-pill": { flex: "none" },
  ".cm-math-pill": {
    border: "0",
    padding: "0 9px",
    borderRadius: "9999px",
    backgroundColor: "transparent",
    color: muted,
    fontFamily: "var(--font-sans)",
    fontSize: "12px",
    lineHeight: "22px",
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "background-color 120ms, color 120ms",
  },
  ".cm-math-mode, .cm-math-shape": { flex: "none", color: "var(--color-foreground)", fontWeight: "500" },
  ".cm-math-mode[hidden], .cm-math-shape[hidden]": { display: "none" },
  ".cm-math-close": {
    flex: "none",
    width: "22px",
    height: "22px",
    display: "grid",
    placeItems: "center",
    padding: "0",
    border: "0",
    borderRadius: "9999px",
    backgroundColor: "transparent",
    color: muted,
    cursor: "pointer",
    transition: "background-color 120ms, color 120ms",
  },
  ".cm-math-close:hover": { backgroundColor: "var(--color-accent)", color: "var(--color-foreground)" },
  ".cm-math-pill:hover": { backgroundColor: "var(--color-accent)", color: "var(--color-foreground)" },
  ".cm-math-pill[aria-pressed=true]": { backgroundColor: "var(--color-accent)", color: "var(--color-foreground)" },
  ".cm-math-recents": {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    marginTop: "6px",
  },
  ".cm-math-recents[hidden]": { display: "none" },
  ".cm-math-caption": { flex: "none", color: muted, fontSize: "11px", marginRight: "4px" },
  // One row that scrolls sideways, like the tab strip.
  ".cm-math-recent-cells": {
    flex: "1",
    minWidth: "0",
    display: "flex",
    alignItems: "center",
    gap: "2px",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  ".cm-math-recent-cells::-webkit-scrollbar": { display: "none" },
  ".cm-math-recents .cm-math-cell": { flex: "none", width: "36px" },
  ".cm-math-recents .cm-math-cell-wide": { width: "74px" },
  // Three rows of cells (32px + 2px gaps); the rest scrolls.
  // Faded top and bottom like the tab strip.
  ".cm-math-body": {
    marginTop: "6px",
    maxHeight: "100px",
    overflowY: "auto",
    overflowX: "hidden",
  },
  ".cm-math-grid": {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(36px, 1fr))",
    gridAutoFlow: "row dense",
    gap: "2px",
  },
  // Rows grow for a two-line preview (cases, matrices).
  ".cm-math-cell": {
    minHeight: "32px",
    minWidth: "0",
    border: "0",
    padding: "4px 2px",
    borderRadius: "6px",
    backgroundColor: "transparent",
    color: "var(--color-foreground)",
    fontSize: "11px",
    overflow: "hidden",
    cursor: "pointer",
    transition: "background-color 120ms",
  },
  ".cm-math-cell-wide": { gridColumn: "span 2" },
  ".cm-math-cell:hover": { backgroundColor: "var(--color-accent)" },
  ".cm-math-cell .katex": { cursor: "pointer" },
  // The chip under pasted maths: one row, its switch and close button.
  // After `.cm-math-tools`, which it overrides; `-hidden` still beats it.
  ".cm-math-pasted": {
    width: "auto",
    display: "flex",
    alignItems: "center",
    gap: "2px",
    padding: "4px",
  },
  ".cm-math-pasted .cm-math-close": { marginLeft: "2px" },
  ".cm-math-matrix": { display: "flex", alignItems: "flex-start", gap: "12px", marginBottom: "8px" },
  ".cm-math-matrix-grid": { display: "grid", gridTemplateColumns: "repeat(6, 14px)", gap: "2px" },
  ".cm-math-matrix-cell": {
    width: "14px",
    height: "14px",
    padding: "0",
    border: "1px solid var(--color-border)",
    borderRadius: "3px",
    backgroundColor: "var(--color-card)",
    cursor: "pointer",
  },
  ".cm-math-matrix-cell.cm-math-matrix-lit": {
    borderColor: brand,
    backgroundColor: "var(--color-brand-muted)",
  },
  ".cm-math-matrix-side": { display: "flex", flexDirection: "column", gap: "6px" },
  ".cm-math-matrix-size": { color: muted, fontSize: "11px", fontVariantNumeric: "tabular-nums" },
};
