//! Background session keep-alive via a macOS LaunchAgent.
//!
//! The Canvas session has no cookie-side expiry — the server tracks it and
//! extends it on use — so a periodic ping keeps it alive, but only while
//! something is making requests. The in-app timer covers "Oculus is open"; this
//! covers the rest by handing the same job to launchd, which runs whether or
//! not the app is.
//!
//! Trade-off worth knowing: the agent is a standalone script that reads and
//! rewrites the plaintext cookie file on a schedule. It cannot beat an absolute
//! session cap or an SSO policy that forces re-auth — when those fire you still
//! sign in by hand.

use tauri::{AppHandle, Manager};

pub const LABEL: &str = "com.tchan.oculus.session-keepalive";
const DEFAULT_INTERVAL_HOURS: u32 = 6;

#[derive(serde::Serialize)]
pub struct KeepaliveStatus {
    /// False on platforms with no LaunchAgent support.
    pub supported: bool,
    pub enabled: bool,
    pub interval_hours: u32,
    /// Last line the agent logged, so the UI can show it is actually running.
    pub last_run: Option<String>,
}

fn script_path(app: &AppHandle) -> std::path::PathBuf {
    app.path()
        .app_data_dir()
        .expect("no app data dir")
        .join("session-keepalive.sh")
}

fn log_path(app: &AppHandle) -> std::path::PathBuf {
    app.path()
        .app_data_dir()
        .expect("no app data dir")
        .join("session-keepalive.log")
}

fn plist_path() -> Option<std::path::PathBuf> {
    let home = std::env::var_os("HOME")?;
    Some(
        std::path::PathBuf::from(home)
            .join("Library/LaunchAgents")
            .join(format!("{LABEL}.plist")),
    )
}

/// The agent script: ping Canvas with the saved cookie, then fold any rotated
/// cookies back into the file. Mirrors `auth::merge_set_cookies` in shell so it
/// can run with the app closed.
fn script_body(cookie: &str, log: &str) -> String {
    format!(
        r#"#!/bin/sh
# Oculus session keep-alive — generated by Oculus, edits will be overwritten.
# Rolls the Canvas session forward and stores the rotated cookie.

COOKIE="{cookie}"
LOG="{log}"
URL="{base}/api/v1/users/self"

[ -s "$COOKIE" ] || exit 0

HDR=$(mktemp) || exit 0
trap 'rm -f "$HDR"' EXIT

CODE=$(curl -s -o /dev/null -D "$HDR" -w '%{{http_code}}' --max-time 30 \
    -H "Cookie: $(cat "$COOKIE")" "$URL" 2>/dev/null)

if [ "$CODE" != "200" ]; then
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) ping failed: HTTP ${{CODE:-000}}" >> "$LOG"
    exit 0
fi

NEW=$(awk -v cookie_file="$COOKIE" '
BEGIN {{
    cnt = 0
    if ((getline line < cookie_file) > 0) {{
        m = split(line, parts, ";")
        for (i = 1; i <= m; i++) {{
            p = parts[i]
            gsub(/^[ \t]+|[ \t]+$/, "", p)
            if (p == "") continue
            eq = index(p, "=")
            if (eq == 0) continue
            name = substr(p, 1, eq - 1)
            if (!(name in seen)) {{ cnt++; order[cnt] = name; seen[name] = 1 }}
            value[name] = substr(p, eq + 1)
        }}
    }}
}}
tolower($1) == "set-cookie:" {{
    rest = substr($0, index($0, ":") + 1)
    gsub(/\r/, "", rest)
    semi = index(rest, ";")
    if (semi > 0) rest = substr(rest, 1, semi - 1)
    gsub(/^[ \t]+|[ \t]+$/, "", rest)
    eq = index(rest, "=")
    if (eq == 0) next
    name = substr(rest, 1, eq - 1)
    if (!(name in seen)) {{ cnt++; order[cnt] = name; seen[name] = 1 }}
    value[name] = substr(rest, eq + 1)
}}
END {{
    out = ""
    for (i = 1; i <= cnt; i++) {{
        name = order[i]
        out = out (i > 1 ? "; " : "") name "=" value[name]
    }}
    if (out != "") print out
}}
' "$HDR")

# The ping itself is what extends the session; a rotated cookie is a bonus
# Canvas only sends sometimes, so only rewrite when the header actually moved.
if [ -n "$NEW" ] && [ "$NEW" != "$(cat "$COOKIE")" ]; then
    printf '%s' "$NEW" > "$COOKIE.tmp" && chmod 600 "$COOKIE.tmp" && mv "$COOKIE.tmp" "$COOKIE"
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) session extended, cookie rotated" >> "$LOG"
else
    echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) session extended" >> "$LOG"
fi

# Keep the log from growing without bound.
if [ -f "$LOG" ]; then
    tail -n 200 "$LOG" > "$LOG.tmp" 2>/dev/null && mv "$LOG.tmp" "$LOG"
fi
"#,
        cookie = cookie,
        log = log,
        base = crate::auth::CANVAS_BASE,
    )
}

fn plist_body(script: &str, interval_secs: u32) -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>{script}</string>
    </array>
    <key>StartInterval</key>
    <integer>{interval_secs}</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>ProcessType</key>
    <string>Background</string>
</dict>
</plist>
"#
    )
}

#[cfg(target_os = "macos")]
fn gui_domain() -> Result<String, String> {
    let out = std::process::Command::new("id")
        .arg("-u")
        .output()
        .map_err(|e| format!("could not determine uid: {e}"))?;
    let uid = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if uid.is_empty() {
        return Err("could not determine uid".to_string());
    }
    Ok(format!("gui/{uid}"))
}

#[cfg(target_os = "macos")]
fn launchctl(args: &[&str]) -> Result<(), String> {
    let out = std::process::Command::new("launchctl")
        .args(args)
        .output()
        .map_err(|e| format!("launchctl: {e}"))?;
    if out.status.success() {
        return Ok(());
    }
    Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
}

fn last_log_line(app: &AppHandle) -> Option<String> {
    let text = std::fs::read_to_string(log_path(app)).ok()?;
    text.lines().last().map(str::to_string)
}

fn interval_from_plist(path: &std::path::Path) -> u32 {
    let Ok(text) = std::fs::read_to_string(path) else {
        return DEFAULT_INTERVAL_HOURS;
    };
    // Small enough to scan rather than pull in a plist parser.
    let Some(after) = text.split("<key>StartInterval</key>").nth(1) else {
        return DEFAULT_INTERVAL_HOURS;
    };
    let Some(open) = after.find("<integer>") else {
        return DEFAULT_INTERVAL_HOURS;
    };
    let rest = &after[open + "<integer>".len()..];
    let Some(close) = rest.find("</integer>") else {
        return DEFAULT_INTERVAL_HOURS;
    };
    rest[..close]
        .trim()
        .parse::<u32>()
        .map(|secs| (secs / 3600).max(1))
        .unwrap_or(DEFAULT_INTERVAL_HOURS)
}

// ── Tauri commands ───────────────────────────────────────────────────────────

#[tauri::command]
pub fn keepalive_status(app: AppHandle) -> KeepaliveStatus {
    let supported = cfg!(target_os = "macos");
    let plist = plist_path();
    let enabled = supported && plist.as_ref().is_some_and(|p| p.exists());
    let interval_hours = match (&plist, enabled) {
        (Some(p), true) => interval_from_plist(p),
        _ => DEFAULT_INTERVAL_HOURS,
    };

    KeepaliveStatus {
        supported,
        enabled,
        interval_hours,
        last_run: if enabled { last_log_line(&app) } else { None },
    }
}

/// Install (or re-install, to change the interval) the LaunchAgent.
#[tauri::command]
pub async fn keepalive_enable(app: AppHandle, interval_hours: u32) -> Result<(), String> {
    #[cfg(not(target_os = "macos"))]
    {
        let _ = (app, interval_hours);
        Err("Background keep-alive is macOS-only.".to_string())
    }

    #[cfg(target_os = "macos")]
    {
        // A token needs no keep-alive, and an empty cookie file means there is
        // nothing to keep alive yet.
        if crate::auth::saved_cookie_header(&app).is_empty() {
            return Err("No saved session to keep alive — connect to Canvas first.".to_string());
        }

        let hours = interval_hours.clamp(1, 24);
        let plist = plist_path().ok_or("no HOME directory")?;
        let script = script_path(&app);
        let cookie = app
            .path()
            .app_data_dir()
            .map_err(|e| e.to_string())?
            .join("canvas-session.cookie");

        std::fs::write(
            &script,
            script_body(&cookie.to_string_lossy(), &log_path(&app).to_string_lossy()),
        )
        .map_err(|e| format!("could not write agent script: {e}"))?;
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o700)).ok();
        }

        if let Some(dir) = plist.parent() {
            std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
        }
        std::fs::write(
            &plist,
            plist_body(&script.to_string_lossy(), hours * 3600),
        )
        .map_err(|e| format!("could not write LaunchAgent: {e}"))?;

        let domain = gui_domain()?;
        let plist_str = plist.to_string_lossy().to_string();
        // Replacing an existing agent: bootout first, and ignore the error when
        // nothing was loaded.
        let _ = launchctl(&["bootout", &domain, &plist_str]);
        launchctl(&["bootstrap", &domain, &plist_str]).map_err(|e| {
            // Leave no half-installed agent behind.
            std::fs::remove_file(&plist).ok();
            format!("launchctl refused the agent: {e}")
        })?;

        eprintln!("[oculus] keep-alive agent installed ({hours}h)");
        Ok(())
    }
}

#[tauri::command]
pub async fn keepalive_disable(app: AppHandle) -> Result<(), String> {
    #[cfg(not(target_os = "macos"))]
    {
        let _ = app;
        Ok(())
    }

    #[cfg(target_os = "macos")]
    {
        if let Some(plist) = plist_path() {
            if plist.exists() {
                let plist_str = plist.to_string_lossy().to_string();
                if let Ok(domain) = gui_domain() {
                    let _ = launchctl(&["bootout", &domain, &plist_str]);
                }
                std::fs::remove_file(&plist).map_err(|e| e.to_string())?;
            }
        }
        std::fs::remove_file(script_path(&app)).ok();
        eprintln!("[oculus] keep-alive agent removed");
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Emits the real generated agent + plist so they can be exercised outside
    /// the app. Set OCULUS_DUMP_AGENT=<dir>; otherwise this is a no-op.
    #[test]
    fn dump_agent_artifacts() {
        let Some(dir) = std::env::var_os("OCULUS_DUMP_AGENT") else {
            return;
        };
        let dir = std::path::PathBuf::from(dir);
        let script = dir.join("agent.sh");
        std::fs::write(
            &script,
            script_body(
                &dir.join("cookie.txt").to_string_lossy(),
                &dir.join("agent.log").to_string_lossy(),
            ),
        )
        .unwrap();
        std::fs::write(
            dir.join("agent.plist"),
            plist_body(&script.to_string_lossy(), 6 * 3600),
        )
        .unwrap();
    }

    #[test]
    fn interval_round_trips_through_the_plist() {
        let dir = std::env::temp_dir().join("oculus-plist-test");
        std::fs::create_dir_all(&dir).unwrap();
        let p = dir.join("t.plist");
        std::fs::write(&p, plist_body("/tmp/agent.sh", 6 * 3600)).unwrap();
        assert_eq!(interval_from_plist(&p), 6);
        // A malformed plist must fall back, not panic.
        std::fs::write(&p, "not a plist").unwrap();
        assert_eq!(interval_from_plist(&p), DEFAULT_INTERVAL_HOURS);
    }
}
