// Writes src/markdown/tables.rs from the app's real parser and the JS regex
// engine: the node types in nodeSet order, and the BMP ranges of the two
// character classes the inline parser tests one UTF-16 unit at a time
// (`Punctuation` = /[\p{S}|\p{P}]/u and /\s/). `oracle/markdown.ts` checks the
// node list against the live parser on every run.
//
//   bun editor-core/oracle/markdown-tables.ts      (from app/)

import { join } from "node:path";

import { noteLanguage } from "../../src/components/documents/editor/core/language";
import { crate } from "./driver";

const types: string[] = (noteLanguage.parser as unknown as { nodeSet: { types: { name: string }[] } }).nodeSet.types.map(
  (t) => t.name,
);

function ranges(test: (s: string) => boolean): [number, number][] {
  const out: [number, number][] = [];
  for (let c = 0; c <= 0xffff; c++) {
    if (!test(String.fromCharCode(c))) continue;
    const last = out[out.length - 1];
    if (last && last[1] === c - 1) last[1] = c;
    else out.push([c, c]);
  }
  return out;
}

const punctuation = ranges((s) => /[\p{S}|\p{P}]/u.test(s));
const space = ranges((s) => /\s/.test(s));
const hex = (n: number) => `0x${n.toString(16).toUpperCase().padStart(4, "0")}`;
const table = (rs: [number, number][]) => rs.map(([a, b]) => `    (${hex(a)}, ${hex(b)}),`).join("\n");

const src = `//! Generated by \`oracle/markdown-tables.ts\` from the app's parser and the JS
//! regex engine; do not edit by hand.

/// Node types in \`@lezer/markdown\`'s \`nodeSet\` order for the app's
/// configuration (\`editor/core/language.ts\`). Id 0 is Lezer's anonymous \`none\`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(u8)]
pub enum NodeType {
${types.map((n, i) => `    ${i === 0 ? "None" : n} = ${i},`).join("\n")}
}

impl NodeType {
    /// Every type, by id.
    pub const ALL: [NodeType; ${types.length}] = [
${types.map((n, i) => `        NodeType::${i === 0 ? "None" : n},`).join("\n")}
    ];

    /// Lezer's name for the type (\`""\` for \`None\`).
    pub fn name(self) -> &'static str {
        match self {
${types.map((n, i) => `            NodeType::${i === 0 ? "None" : n} => "${n}",`).join("\n")}
        }
    }
}

/// BMP code points matching \`/[\\p{S}|\\p{P}]/u\`, as inclusive ranges.
pub(crate) const PUNCTUATION: &[(u16, u16)] = &[
${table(punctuation)}
];

/// BMP code points matching JS \`/\\s/\`, as inclusive ranges.
pub(crate) const JS_SPACE: &[(u16, u16)] = &[
${table(space)}
];
`;

const out = join(crate, "src/markdown/tables.rs");
await Bun.write(out, src);
Bun.spawnSync(["rustfmt", "--edition", "2024", out], { stdout: "inherit", stderr: "inherit" });
console.log(`tables.rs: ${types.length} node types, ${punctuation.length} punctuation ranges, ${space.length} space ranges`);
